apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ include "mysql.fullname" . }}-port
    - port: {{ .Values.service.port }}0
      targetPort: {{ .Values.service.targetPort }}0
      protocol: TCP
      name: {{ include "mysql.fullname" . }}-port-alt
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
